### ISSUE TITLE
关于Swiper滑块视图容器

### ISSUE THREAD

**Issue by huangguozhen** [NervJS/taro-ui-demo#1]
扫描小程序二维码的例子中有个Swiper滑块视图容器，代码中找不到这个容器的相关代码

**Comment by koppthe** [comment]
这个 `taro-ui-demo` 的项目不是线上 taro ui 小程序的源码，仅仅是用来测试 taro-ui 的版本用的。如果需要找源码，请到 `taro-ui` 项目查看哦
