### ISSUE TITLE
demo无法运行H5 dev版本

### ISSUE THREAD

**Issue by wuzitu** [NervJS/taro-ui-demo#3]
启动报错，demo无法执行H5版本的dev环境。
看起来像是webpack loader的问题，请定位，谢谢。
问题信息：
创建  发现文件  src\pages\view\timeline\index.scss                                                                                                                ./node_modules/_taro-ui@1.5.4@taro-ui/dist/h5/components/pagination/index.js 101 :11                                                                              Module parse failed: Unexpected token (101:11)                                   You may need an appropriate loader to handle this file type.                     \|     };                                                                         \|                                                                                >     return  className)} style={customStyle}>                                                 \|                                       \|
--

**Comment by wuzitu** [comment]
补充运行环境：
nodejs v10.14.2  npm 6.4.1

**Comment by chant520** [comment]
把`node_modules`目录删了重新`npm install i` 或者`cnpm install i`， 也许可以解决。反正我至少安装了四遍才弄好╮(╯▽╰)╭
