### ISSUE TITLE
运行npm run dev:weapp时编译停滞

### ISSUE THREAD

**Issue by guowenxi** [NervJS/taro-ui-demo#4]
生成  依赖文件  dist/npm/lodash/identity.js
生成  依赖文件  dist/npm/lodash/_copyArray.js
生成  依赖文件  dist/npm/lodash/_Symbol.js
生成  依赖文件  dist/npm/lodash/isArguments.js
生成  依赖文件  dist/npm/lodash/_getNative.js

一直停滞在这里,

**Comment by summer-yyyn** [comment]
同问

**Comment by Rebecca-yh** [comment]
同问

**Comment by FrankFan** [comment]
这都没人回复，又是一个KPI产物？？ 
质量堪忧啊

**Comment by koppthe** [comment]
@FrankFan 你这边也有一样的问题吗？
