### ISSUE TITLE
官方DEMO都无法运行，什么情况

### ISSUE THREAD

**Issue by sananiki** [NervJS/taro-ui-demo#6]
npm run dev:h5   之前另一个项目怎么设置都没用，各种文档什么都看了，实在没办法，来下载了官方demo，结果一运行还是报同样的错。
node 版本：v 10.14.0
./node_modules/.2.0.1@taro-ui/dist/h5/components/countdown/index.js 105:11
Module parse failed: Unexpected token (105:11)
You may need an appropriate loader to handle this file type.
|     } = this.state;
|
>     return <View className={classNames({
|       'at-countdown': true,
|       'at-countdown--card': isCard

**Comment by koppthe** [comment]
麻烦配置一下 `esnextModules`

**Comment by sananiki** [comment]
楼上的兄弟，demo里这都是配好的，那是最基本的
