### ISSUE TITLE
It cannot run, lazy official JD guys.

### ISSUE THREAD

**Issue by Mon-ius** [NervJS/taro-ui-demo#8]
My OS : 

`MAC OSX 10.14.3 (18D109)`

My Node version :  
```
node -v
v10.15.1
```

My npm version:

```
 npm -v
6.9.0
```

I init node env from zero, and follow your steps and failed.

- brew install node
- npm install -g npm
- npm install -g @tarojs/cli

> npm WARN deprecated babel-plugin-remove-dead-code@1.3.2: use babel-plugin-minify-dead-code-elimination and babel-plugin-minify-guarded-expressions
> npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

- git clone https://github.com/NervJS/taro-ui-demo
- cd taro-ui-demo
- npm i

```
npm WARN deprecated babel-plugin-remove-dead-code@1.3.2: use babel-plugin-minify-dead-code-elimination and babel-plugin-minify-guarded-expressions
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
WARN tarball tarball data for @tarojs/transformer-wx@1.2.8 (sha1-4NjbtLrTnE+VjmdLBzd6js3v3wY=) seems to be corrupted. Trying one more time.
WARN tarball tarball data for @tarojs/transformer-wx@1.2.8 (sha1-4NjbtLrTnE+VjmdLBzd6js3v3wY=) seems to be corrupted. Trying one more time.
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting @tarojs/transformer-wx@1.2.8:
npm ERR! Verification failed while extracting @tarojs/transformer-wx@1.2.8:
npm ERR! sha1-4NjbtLrTnE+VjmdLBzd6js3v3wY= integrity checksum failed when using sha1: wanted sha1-4NjbtLrTnE+VjmdLBzd6js3v3wY= but got sha512-ezLEsZCakmCcGxM5WjcNxkJNPcUpiQGSQPt4DfKxS26EvJGlr+zznfMH8nGzCbnz9AskrmeUoTirESeZX7vVDA== sha1-8pEqWmfepsNUc+GuugGnHIYdxzQ=. (49119 bytes)

npm ERR! A complete log of this run can be found in:
/.npm/_logs/2019-03-19T19_07_50_434Z-debug.log
```

**I cannot believe such big official repo could leave such big mistakes for month, if you are not going to maintain, please remove it!**

**Comment by JackonLiu** [comment]
I can run 
please use 
yarn 
yarn dev:h5
check your log

**Comment by chris-zh** [comment]
项目跑不起来就删掉吧，别给中国人抹黑了
